services:
  postgres:
    restart: always
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8081:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    entrypoint: >
      /bin/sh -c "
      mkdir -p /var/lib/pgadmin/storage/admin_admin.com;
      echo 'postgres:*:*:postgres:postgres' > /var/lib/pgadmin/storage/admin_admin.com/pgpass;
      chmod 600 /var/lib/pgadmin/storage/admin_admin.com/pgpass;
      /entrypoint.sh
      "
    depends_on:
      - postgres

  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres_data:
  pgadmin_data:
